// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ztwadztyybxkdxcpjgsv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inp0d2FkenR5eWJ4a2R4Y3BqZ3N2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE5OTA0NjcsImV4cCI6MjA2NzU2NjQ2N30.9AtwMPrLDbMjHweZQHyHOg0XZOg-v49kKzWpsnikW9M";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});